### PR TITLE
Fixed overflow line breaks in zh text

### PR DESCRIPTION
**Pull request by NineDays-SuYue**

### CODE REVIEW

**Comment by baka-gourd** [comment]
it will affect all site and fix size is bad

**Comment by NineDays-SuYue** [comment]
> 它会影响所有站点并且修复大小很糟糕

Style source dependency does not modify width

**Comment by NineDays-SuYue** [comment]
> 它会影响所有站点并且修复大小很糟糕

样式来源依赖没法修改宽度

**Comment by NineDays-SuYue** [comment]
There's no way to change the width of a style source dependency.
Unless it's possible to go on a separate class name to modify the style.

**Comment by NineDays-SuYue** [comment]
> 它会影响所有站点并且修复大小很糟糕

There's no way to change the width of a style source dependency.
Unless it's possible to go on a separate class name to modify the style.

**Comment by NineDays-SuYue** [comment]
> it will affect all site and fix size is bad
There's no way to change the width of a style source dependency.
Unless it's possible to go on a separate class name to modify the style.

**Comment by NineDays-SuYue** [comment]
> it will affect all site and fix size is bad

There's no way to change the width of a style source dependency.
Unless it's possible to go on a separate class name to modify the style.

**Pull request closed without merging**
